version: "3.9"

services:
  fip-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fip-bot-agent
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: fip-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fip
      POSTGRES_USER: fipuser
      POSTGRES_PASSWORD: fippass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
