version: "3.9"

services:
  fip-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8081:8080"  # Optional if bot ever runs a web service

  auth-server:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: auth
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: fipauth
      POSTGRES_USER: fipuser
      POSTGRES_PASSWORD: fippass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: