version: "3.9"

services:
  fip-bot:
    build: .
    container_name: agent
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8081:8080"  # Optional if bot ever runs a web service
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: fip-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fip
      POSTGRES_USER: fipuser
      POSTGRES_PASSWORD: fippass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: