name: Build & Test Docker Image

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 🐳 Build Docker image
      run: docker build -t fip-bot-agent .

    - name: ⬆️ Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: .
        retention-days: 1

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: fipuser
          POSTGRES_PASSWORD: fippass
          POSTGRES_DB: fip
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://fipuser:fippass@localhost:5432/fip
      BOT_TOKEN: dummy_token
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      FIP_MAIN: https://icecast.radiofrance.fr/fip-midfi.mp3?id=radiofrance
      FIP_ROCK: https://icecast.radiofrance.fr/fiprock-midfi.mp3?id=radiofrance
      FIP_JAZZ: https://icecast.radiofrance.fr/fipjazz-midfi.mp3?id=radiofrance
      FIP_GROOVE: https://icecast.radiofrance.fr/fipgroove-midfi.mp3?id=radiofrance
      FIP_WORLD: https://icecast.radiofrance.fr/fipworld-midfi.mp3?id=radiofrance
      FIP_NOUVEAUTES: https://icecast.radiofrance.fr/fipnouveautes-midfi.mp3?id=radiofrance
      FIP_REGGAE: https://icecast.radiofrance.fr/fipreggae-midfi.mp3?id=radiofrance
      FIP_ELECTRO: https://icecast.radiofrance.fr/fipelectro-midfi.mp3?id=radiofrance
      FIP_HIPHOP: https://icecast.radiofrance.fr/fiphiphop-midfi.mp3?id=radiofrance
      FIP_POP: https://icecast.radiofrance.fr/fippop-midfi.mp3?id=radiofrance
      FIP_METAL: https://icecast.radiofrance.fr/fipmetal-midfi.mp3?id=radiofrance

    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 🔍 Dry-run Python bytecode check
      run: |
        docker run --rm \
          -e DATABASE_URL=$DATABASE_URL \
          -e BOT_TOKEN=$BOT_TOKEN \
          -e SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID \
          -e SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET \
          -e FIP_MAIN=$FIP_MAIN \
          -e FIP_ROCK=$FIP_ROCK \
          -e FIP_JAZZ=$FIP_JAZZ \
          -e FIP_GROOVE=$FIP_GROOVE \
          -e FIP_WORLD=$FIP_WORLD \
          -e FIP_NOUVEAUTES=$FIP_NOUVEAUTES \
          -e FIP_REGGAE=$FIP_REGGAE \
          -e FIP_ELECTRO=$FIP_ELECTRO \
          -e FIP_HIPHOP=$FIP_HIPHOP \
          -e FIP_POP=$FIP_POP \
          -e FIP_METAL=$FIP_METAL \
          fip-bot-agent python -m py_compile bot.py

    - name: 🧪 Test Spotify track fetch
      run: |
        pip install -r requirements.txt
        PYTHONPATH=. python tests/test_spotify.py

    - name: 🧪 Test Metadata Embed Builder
      run: |
        pip install -r requirements.txt
        PYTHONPATH=. python tests/test_metadata.py